name: Validate Actividad 00

on: [pull_request, push]

jobs:
  ubuntu-build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2.0.0

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install tools
      run: |
        cmake --version
        python --version
        python -m pip install --upgrade pip
        python -m pip install conan
        conan --version
        conan config init
        conan profile update settings.compiler.libcxx=libstdc++11 default
        conan profile show default

    - name: Compile
      run: |
        ls -la
        mkdir _build && cd _build
        ls -la ..
        conan install ../conanfile.txt -s build_type=Release
        cmake .. -DCMAKE_MODULE_PATH=$(pwd)
        cmake --build .

    - name: Run tests
      working-directory: _build
      run: |
        ./unit_tests
