name: Validate Actividad 00

on: [pull_request, push]

jobs:
  ubuntu-build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2.0.0

    - name: Install tools
      run: |
        cmake --version
        python --version
        python -m pip install --user -U conan
        conan --version
        conan profile show default

    - name: Compile
      run: |
        mkdir _build && cd _build
        conan install ../conanfile.txt -s build_type=Release
        cmake .. -DCMAKE_MODULE_PATH=$(pwd)
        cmake --build .

    - name: Run tests
      working-directory: _build
      run: |
        ./unit_tests
