on:
  push:
    branches:
      - main

name: Generate GitHub pages

jobs:
  github-pages:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install jinja2 PyYAML
    - name: Generate files
      run: |
        ls -la
        python template.py
        rm .gitignore
        rm .gitmodules
        rm -fr .git
        rm -fr .github
        ls -la

    - name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@3.7.1
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages # The branch the action should deploy to.
        FOLDER: . # The folder the action should deploy.
        CLEAN: true # Automatically remove deleted files from the deploy branch
        PRESERVE: true  # Preserve files changed
